### ISSUE TITLE
Allow image field to exist anywhere

### ISSUE THREAD

**Issue by mindfullsilence** [Androlax2/acf-image-map#28]
The Point.js script currently restricts the image map field to being inside a repeater, and the linked image field to being a sibling of the repeater, otherwise the map image doesn't load and console errors with `"Could not find a match for the linked image"`.

The following is a non-breaking change that allows the image field to exist anywhere. I wasn't able to get gulp to build the project (node-sass is particularly difficult to get running on apple silicon) or I would have submitted a PR, but the following works with current functionality, and expands the search to the closest container that contains the expected image, regardless of where it is placed tangential to the map image, and regardless of whether the map image is inside a repeater.

**assets/js/Shapes/Point.js Line 29-45**
```js
    _getLinkedImage() {
        let img = this.$field.element[0]
            .closest(':has('+this.$field.selector+')')
            .querySelector(this.$field.selector + ' img[data-name="image"]');

        if ( ! img ) {
            console.error('Could not find a match for the linked image');
            return false;
        }

        return jQuery(img);
    }
```

**Comment by mindfullsilence** [comment]
Note this is probably relevant to the `Poly.js` script as well, but it's not a feature I'm using.

**Comment by Androlax2** [comment]
Hi @mindfullsilence, if you want you can make a PR and I can merge that to master and you can test, the CI will build the assets for production

**Comment by Androlax2** [comment]
I fixed the build, you should be able to build styles/scripts now

**Comment by mindfullsilence** [comment]
@Androlax2 all set. PR includes a small edit to the gulpfile (added semicolon) to make the linter happy.
