### ISSUE TITLE
Upgrade Laravel Collection dependency to ^9.0.0

### ISSUE THREAD

**Issue by mindfullsilence** [Androlax2/acf-image-map#3]
Can't install with current version of [Acorns](https://github.com/roots/acorn) unless I downgrade Illuminate/Collection. Package seems to work fine with Collection 9.*

Would you mind adjusting the composer version constraint?

**Comment by Androlax2** [comment]
I don't have time to take care of this plugin if you don't mind making a PR, I would gladly merge it after testing it
